/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EmploymentApplicationRouteImport } from './routes/employment-application'
import { Route as OnboardingPacketRouteImport } from './routes/onboarding-packet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EmploymentApplicationRoute = EmploymentApplicationRouteImport.update({
  id: '/employment-application',
  path: '/employment-application',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPacketRoute = OnboardingPacketRouteImport.update({
  id: '/onboarding-packet',
  path: '/onboarding-packet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/employment-application': typeof EmploymentApplicationRoute
  '/onboarding-packet': typeof OnboardingPacketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/employment-application': typeof EmploymentApplicationRoute
  '/onboarding-packet': typeof OnboardingPacketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/employment-application': typeof EmploymentApplicationRoute
  '/onboarding-packet': typeof OnboardingPacketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/employment-application' | '/onboarding-packet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/employment-application' | '/onboarding-packet'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/employment-application'
    | '/onboarding-packet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EmploymentApplicationRoute: typeof EmploymentApplicationRoute
  OnboardingPacketRoute: typeof OnboardingPacketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employment-application': {
      id: '/employment-application'
      path: '/employment-application'
      fullPath: '/employment-application'
      preLoaderRoute: typeof EmploymentApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-packet': {
      id: '/onboarding-packet'
      path: '/onboarding-packet'
      fullPath: '/onboarding-packet'
      preLoaderRoute: typeof OnboardingPacketRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EmploymentApplicationRoute: EmploymentApplicationRoute,
  OnboardingPacketRoute: OnboardingPacketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
